# Generated by Django 2.1.2 on 2018-10-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='github_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin_account',
        ),
        migrations.RemoveField(
            model_name='user',
            name='personal_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_account',
        ),
    ]
