# Generated by Django 2.1.2 on 2018-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ksko',
            field=models.BooleanField(default=False),
        ),
    ]
