# Generated by Django 2.1.2 on 2018-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_ksko'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('8', '8th Class'), ('9', '9th Class'), ('10', '10th Class')], max_length=20, verbose_name='Class')),
                ('venue', models.CharField(choices=[('venue1', 'venue1'), ('venue2', 'venue2'), ('venue3', 'venue3')], max_length=20, verbose_name='Class')),
            ],
        ),
    ]
