# Generated by Django 2.1.2 on 2018-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='venue',
            field=models.CharField(choices=[('venue1', 'venue1'), ('venue2', 'venue2'), ('venue3', 'venue3')], max_length=20, verbose_name='Exam Center'),
        ),
    ]
